#
# This file configures the New Relic Agent.  New Relic monitors Ruby, Java,
# .NET, PHP, Python and Node applications with deep visibility and low
# overhead.  For more information, visit www.newrelic.com.
#
# Generated June 19, 2017
#
# This configuration file is custom generated for Flatiron School_4
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration

DEFAULT_SETTINGS: &DEFAULT_SETTINGS
  # Required license key associated with your New Relic account.
  license_key: 17b4185fdfd89c6ab2923d9db6e48cba6b93da47

  # Your application name. Renaming here affects where data displays in New
  # Relic.  For more details, see https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/renaming-applications
  app_name: Wiki Api

  # To disable the agent regardless of other settings, uncomment the following:
  # agent_enabled: false

  # Logging level for log/newrelic_agent.log
  log_level: info


# Environment-specific settings are in this section.
# RAILS_ENV or RACK_ENV (as appropriate) is used to determine the environment.
# If your application has other named environments, configure them here.
development:
  <<: *DEFAULT_SETTINGS
  app_name: Wiki Api (Development)
  monitor_mode: true

test:
  <<: *DEFAULT_SETTINGS
  # It doesn't make sense to report to New Relic from automated test runs.
  monitor_mode: false

staging:
  <<: *DEFAULT_SETTINGS
  app_name: Wiki Api (Staging)

production:
  <<: *DEFAULT_SETTINGS
